import { defineStore } from "pinia";

export const usePlayersListStore = defineStore("playersListStore", {
  state: () => ({
    teams: [
      {
        teamName: "Vince",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Adam",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Max",
        players: [
          {
            id: "10140",
          },
        ],
      },
      {
        teamName: "Jeff",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Bobby",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Emily",
        players: [
          {
            id: "10140",
          },
        ],
      },
      {
        teamName: "Scott",
        players: [
          {
            id: "4364873",
          },
        ],
      },
      {
        teamName: "Jason",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Seth",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Mackenzie",
        players: [
          {
            id: "6798",
          },
        ],
      },
      {
        teamName: "RJ",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "M.Kaiser",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Joe K",
        players: [
          {
            id: "9478",
          },
        ],
      },
      {
        teamName: "Brad",
        players: [
          {
            id: "9478",
          },
        ],
      },
    ],
    tournamentPlayers: [
      { name: "Scottie Scheffler" },
      { name: "Rory McIlroy" },
      { name: "Xander Schauffele" },
      { name: "Brooks Koepka" },
      { name: "Jon Rahm" },
      { name: "Ludvig Aberg" },
      { name: "Bryson DeChambeau" },
      { name: "Collin Morikawa" },
      { name: "Max Homa" },
      { name: "Joaquin Niemann" },
      { name: "Patrick Cantlay" },
      { name: "Cameron Smith" },
      { name: "Wyndham Clark" },
      { name: "Viktor Hovland" },
      { name: "Tommy Fleetwood" },
      { name: "Tyrrell Hatton" },
      { name: "Justin Thomas" },
      { name: "Cameron Young" },
      { name: "Jason Day" },
      { name: "Hideki Matsuyama" },
      { name: "Byeong Hun An" },
      { name: "Sam Burns" },
      { name: "Sahith Theegala" },
      { name: "Matt Fitzpatrick" },
      { name: "Min Woo Lee" },
      { name: "Sungjae Im" },
      { name: "Si Woo Kim" },
      { name: "Will Zalatoris" },
      { name: "Tony Finau" },
      { name: "Sepp Straka" },
      { name: "Jordan Spieth" },
      { name: "Dustin Johnson" },
      { name: "Talor Gooch" },
      { name: "Russell Henley" },
      { name: "Corey Conners" },
      { name: "Shane Lowry" },
      { name: "Denny McCarthy" },
      { name: "Adam Scott" },
      { name: "Dean Burmester" },
      { name: "Alex Noren" },
      { name: "Akshay Bhatia" },
      { name: "Tom Kim" },
      { name: "Stephan Jaeger" },
      { name: "Nicolai Hojgaard" },
      { name: "Kurt Kitayama" },
      { name: "Keith Mitchell" },
      { name: "Chris Kirk" },
      { name: "Taylor Pendrith" },
      { name: "Patrick Reed" },
      { name: "Mackenzie Hughes" },
      { name: "Keegan Bradley" },
      { name: "Harris English" },
      { name: "Christiaan Bezuidenhout" },
      { name: "Brian Harman" },
      { name: "Jake Knapp" },
      { name: "Ryan Fox" },
      { name: "Rickie Fowler" },
      { name: "Tom Hoge" },
      { name: "Taylor Moore" },
      { name: "Billy Horschel" },
      { name: "J.T. Poston" },
      { name: "Thomas Detry" },
      { name: "Erik Van Rooyen" },
      { name: "Cam Davis" },
      { name: "Tiger Woods" },
      { name: "Justin Rose" },
      { name: "Adam Hadwin" },
      { name: "Matt Wallace" },
      { name: "Eric Cole" },
      { name: "Sebastian Soderberg" },
      { name: "Rasmus Hojgaard" },
      { name: "Nick Taylor" },
      { name: "Matthieu Pavon" },
      { name: "Lucas Glover" },
      { name: "Austin Eckroat" },
      { name: "Adrian Meronk" },
      { name: "Adam Schenk" },
      { name: "Aaron Rai" },
      { name: "Thorbjorn Olesen" },
      { name: "Patrick Rodgers" },
      { name: "Chris Gotterup" },
      { name: "Maverick McNealy" },
      { name: "Beau Hossler" },
      { name: "Nick Dunlap" },
      { name: "Keita Nakajima" },
      { name: "Robert MacIntyre" },
      { name: "Phil Mickelson" },
      { name: "Lucas Herbert" },
      { name: "Jordan Smith" },
      { name: "Brendon Todd" },
      { name: "Ben Griffin" },
      { name: "Andrew Putnam" },
      { name: "Mark Hubbard" },
      { name: "Luke List" },
      { name: "David Puig" },
      { name: "Victor Perez" },
      { name: "Doug Ghim" },
      { name: "Alex Smalley" },
      { name: "Ryo Hisatsune" },
      { name: "Emiliano Grillo" },
      { name: "Lee Hodges" },
      { name: "Alejandro Tosti" },
      { name: "Adam Svensson" },
      { name: "S.H. Kim" },
      { name: "K.H. Lee" },
      { name: "Gary Woodland" },
      { name: "Tim Widing" },
      { name: "Thriston Lawrence" },
      { name: "Charley Hoffman" },
      { name: "Alexander Bjork" },
      { name: "Grayson Murray" },
      { name: "C.T. Pan" },
      { name: "Vincent Norrman" },
      { name: "Takumi Kanaya" },
      { name: "Sami Valimaki" },
      { name: "Peter Malnati" },
      { name: "Brice Garnett" },
      { name: "Adrian Otaegui" },
      { name: "Jesper Svensson" },
      { name: "Ben Kohles" },
      { name: "Andy Ogletree" },
      { name: "Francesco Molinari" },
      { name: "Padraig Harrington" },
      { name: "Martin Kaymer" },
      { name: "Zac Blair" },
      { name: "Luke Donald" },
      { name: "Kazuma Kobori" },
      { name: "Camilo Villegas" },
      { name: "Ryan Van Velzen" },
      { name: "Jason Dufner" },
      { name: "Brad Marek" },
      { name: "Zac Oakley" },
      { name: "Y.E. Yang" },
      { name: "Wyatt Worthington II" },
      { name: "Tyler Collet" },
      { name: "Tracy Phillips" },
      { name: "Shaun Micheel" },
      { name: "Rich Beem" },
      { name: "Preston Cole" },
      { name: "Michael Block" },
      { name: "Matt Dobyns" },
      { name: "Larkin Gross" },
      { name: "Kyle Mendoza" },
      { name: "Josh Speight" },
      { name: "Josh Bevell" },
      { name: "John Somers" },
      { name: "John Daly" },
      { name: "Jimmy Walker" },
      { name: "Jesse Mueller" },
      { name: "Jeremy Wells" },
      { name: "Jeff Kellen" },
      { name: "Jared Jones" },
      { name: "Evan Bowser" },
      { name: "Braden Shattuck" },
      { name: "Andrew Svoboda" },
      { name: "Ben Polland" },
    ],
  }),
});
