import { defineStore } from "pinia";

export const usePlayersListStore = defineStore("playersListStore", {
  state: () => ({
    teams: [
      {
        teamName: "Vince",
        players: [
          { id: "10046" },
          { id: "4587" },
          { id: "9131" },
          { id: "9037" },
          { id: "4382434" },
          { id: "4425906" },
          { id: "3449" },
          { id: "10058" },
          { id: "10596" },
          { id: "4723205" },
        ],
      },
      {
        teamName: "RJ",
        players: [
          { id: "9478" },
          { id: "4587" },
          { id: "8973" },
          { id: "1225" },
          { id: "6086" },
          { id: "3792" },
          { id: "4901368" },
          { id: "6011" },
          { id: "110" },
          { id: "446" },
        ],
      },
      {
        teamName: "Penny",
        players: [
          { id: "9478" },
          { id: "4587" },
          { id: "4419142" },
          { id: "4602673" },
          { id: "388" },
          { id: "3792" },
          { id: "10522" },
          { id: "1030" },
          { id: "4832046" },
          { id: "4590" },
        ],
      },
      {
        teamName: "Jeff",
        players: [
          { id: "3470" },
          { id: "11382" },
          { id: "5830" },
          { id: "10166" },
          { id: "4858859" },
          { id: "4425906" },
          { id: "9243" },
          { id: "10548" },
          { id: "4832046" },
          { id: "3683" },
        ],
      },
      {
        teamName: "Audra",
        players: [
          { id: "9478" },
          { id: "4410932" },
          { id: "9877" },
          { id: "10166" },
          { id: "5408" },
          { id: "11340" },
          { id: "9243" },
          { id: "10548" },
          { id: "601" },
          { id: "4845307" },
        ],
      },
      {
        teamName: "Jason",
        players: [
          { id: "3470" },
          { id: "9025" },
          { id: "4513" },
          { id: "10166" },
          { id: "3550" },
          { id: "4425906" },
          { id: "4404991" },
          { id: "11383" },
          { id: "10596" },
          { id: "4845307" },
        ],
      },
      {
        teamName: "Katie",
        players: [
          { id: "9478" },
          { id: "4587" },
          { id: "4513" },
          { id: "3702" },
          { id: "4382434" },
          { id: "11250" },
          { id: "9243" },
          { id: "5548" },
          { id: "4832046" },
          { id: "4723205" },
        ],
      },
      {
        teamName: "Bobby",
        players: [
          { id: "3470" },
          { id: "4587" },
          { id: "8973" },
          { id: "3702" },
          { id: "388" },
          { id: "4425906" },
          { id: "4901368" },
          { id: "10058" },
          { id: "601" },
          { id: "4723205" },
        ],
      },
      {
        teamName: "Emily",
        players: [
          { id: "10046" },
          { id: "4587" },
          { id: "9938" },
          { id: "10054" },
          { id: "388" },
          { id: "4425906" },
          { id: "10863" },
          { id: "5548" },
          { id: "10596" },
          { id: "3683" },
        ],
      },
      {
        teamName: "Kaiser",
        players: [
          { id: "9478" },
          { id: "5579" },
          { id: "9131" },
          { id: "1225" },
          { id: "4425904" },
          { id: "4425906" },
          { id: "3449" },
          { id: "5147097" },
          { id: "601" },
          { id: "4845307" },
        ],
      },
      {
        teamName: "Seth",
        players: [
          { id: "9478" },
          { id: "4587" },
          { id: "2230" },
          { id: "11332" },
          { id: "4382434" },
          { id: "4425906" },
          { id: "4565467" },
          { id: "6011" },
          { id: "4671" },
          { id: "4723205" },
        ],
      },
      {
        teamName: "Adam",
        players: [
          { id: "10046" },
          { id: "4587" },
          { id: "2230" },
          { id: "10166" },
          { id: "5408" },
          { id: "4425906" },
          { id: "4425898" },
          { id: "4358083" },
          { id: "4832046" },
          { id: "199" },
        ],
      },
      {
        teamName: "Joe",
        players: [
          { id: "9478" },
          { id: "4587" },
          { id: "2230" },
          { id: "10166" },
          { id: "5408" },
          { id: "4425906" },
          { id: "11385" },
          { id: "10548" },
          { id: "4410612" },
          { id: "3683" },
        ],
      },
    ],
    tournamentPlayers: [
      { name: "Scottie Scheffler" },
      { name: "Rory McIlroy" },
      { name: "Bryson DeChambeau" },
      { name: "Jon Rahm" },
      { name: "Xander Schauffele" },
      { name: "Ludvig Aberg" },
      { name: "Justin Thomas" },
      { name: "Collin Morikawa" },
      { name: "Joaquin Niemann" },
      { name: "Brooks Koepka" },
      { name: "Tyrrell Hatton" },
      { name: "Hideki Matsuyama" },
      { name: "Viktor Hovland" },
      { name: "Tommy Fleetwood" },
      { name: "Patrick Cantlay" },
      { name: "Jordan Spieth" },
      { name: "Shane Lowry" },
      { name: "Sepp Straka" },
      { name: "Russell Henley" },
      { name: "Corey Conners" },
      { name: "Jason Day" },
      { name: "Wyndham Clark" },
      { name: "Sungjae Im" },
      { name: "Patrick Reed" },
      { name: "Min Woo Lee" },
      { name: "Justin Rose" },
      { name: "Sergio Garcia" },
      { name: "Daniel Berger" },
      { name: "Robert MacIntyre" },
      { name: "Maverick McNealy" },
      { name: "Keegan Bradley" },
      { name: "Dustin Johnson" },
      { name: "Cameron Smith" },
      { name: "Tony Finau" },
      { name: "Si Woo Kim" },
      { name: "Sam Burns" },
      { name: "Will Zalatoris" },
      { name: "Byeong Hun An" },
      { name: "Akshay Bhatia" },
      { name: "Dean Burmester" },
      { name: "David Puig" },
      { name: "Taylor Pendrith" },
      { name: "Max Homa" },
      { name: "Keith Mitchell" },
      { name: "Aaron Rai" },
      { name: "Tom Kim" },
      { name: "J.J. Spaun" },
      { name: "Denny McCarthy" },
      { name: "Brian Harman" },
      { name: "Matt Fitzpatrick" },
      { name: "Davis Thompson" },
      { name: "Michael Kim" },
      { name: "" },
      { name: "Andrew Novak" },
      { name: "Samuel Stevens" },
      { name: "Thomas Detry" },
      { name: "Stephan Jaeger" },
      { name: "Ryan Fox" },
      { name: "Rickie Fowler" },
      { name: "Rasmus Hojgaard" },
      { name: "Niklas Norgaard" },
      { name: "Harris English" },
      { name: "Adam Scott" },
      { name: "Tom Hoge" },
      { name: "Rasmus Neergaard-Petersen" },
      { name: "Taylor Moore" },
      { name: "Max Greyserman" },
      { name: "Michael Thorbjornsen" },
      { name: "Bud Cauley" },
      { name: "Ben Griffin" },
      { name: "Mackenzie Hughes" },
      { name: "Lucas Glover" },
      { name: "Kurt Kitayama" },
      { name: "J.T. Poston" },
      { name: "Gary Woodland" },
      { name: "Cameron Young" },
      { name: "Thorbjorn Olesen" },
      { name: "Nick Taylor" },
      { name: "Kevin Yu" },
      { name: "Jacob Bridgeman" },
      { name: "Victor Perez" },
      { name: "Phil Mickelson" },
      { name: "Nicolai Hojgaard" },
      { name: "Jake Knapp" },
      { name: "Tom McKibbin" },
      { name: "Erik Van Rooyen" },
      { name: "Seamus Power" },
      { name: "Ryan Gerard" },
      { name: "Laurie Canter" },
      { name: "Harry Hall" },
      { name: "Patrick Rodgers" },
      { name: "Rico Hoey" },
      { name: "Chris Kirk" },
      { name: "Alex Noren" },
      { name: "Matt McCarty" },
      { name: "Lee Hodges" },
      { name: "Eugenio Chacarra" },
      { name: "Eric Cole" },
      { name: "Christiaan Bezuidenhout" },
      { name: "Cam Davis" },
      { name: "Elvis Smylie" },
      { name: "Austin Eckroat" },
      { name: "Ryo Hisatsune" },
      { name: "Keita Nakajima" },
      { name: "Garrick Higgo" },
      { name: "Matt Wallace" },
      { name: "Beau Hossler" },
      { name: "Patrick Fishburn" },
      { name: "Joe Highsmith" },
      { name: "Jhonattan Vegas" },
      { name: "Sami Valimaki" },
      { name: "Davis Riley" },
      { name: "Karl Vilips" },
      { name: "Nico Echavarria" },
      { name: "Max McGreevy" },
      { name: "John Keefer" },
      { name: "Adam Hadwin" },
      { name: "Richard Bland" },
      { name: "Justin Lower" },
      { name: "Marco Penge" },
      { name: "Nick Dunlap" },
      { name: "John Parry" },
      { name: "Takumi Kanaya" },
      { name: "John Catlin" },
      { name: "Matthieu Pavon" },
      { name: "Thriston Lawrence" },
      { name: "Patton Kizzire" },
      { name: "Michael Block" },
      { name: "Jason Dufner" },
      { name: "Brian Campbell" },
      { name: "Daniel van Tonder" },
      { name: "Martin Kaymer" },
      { name: "Luke Donald" },
      { name: "Padraig Harrington" },
      { name: "Andre Chi" },
      { name: "Rafael Campos" },
      { name: "Jimmy Walker" },
      { name: "Tyler Collet" },
      { name: "Shaun Micheel" },
      { name: "Justin Hicks" },
      { name: "Greg Koch" },
      { name: "Timothy Wiseman" },
      { name: "Tom Johnson" },
      { name: "Larkin Gross" },
      { name: "John Somers" },
      { name: "Jesse Droemer" },
      { name: "Bob Sowards" },
      { name: "Ryan Lenahan" },
      { name: "Rupe Taylor" },
      { name: "Nic Ishee" },
      { name: "Michael Kartrude" },
      { name: "Eric Steger" },
      { name: "Dylan Newman" },
      { name: "Brian Bergstol" },
      { name: "Brandon Bingaman" },
      { name: "Bobby Gates" },
    ],
  }),
});
