import { defineStore } from "pinia";

export const usePlayersListStore = defineStore("playersListStore", {
  state: () => ({
    teams: [
      {
        teamName: "Vince",
        players: [
          { id: "9478" },
          { id: "4410932" },
          { id: "9126" },
          { id: "4513" },
          { id: "1651" },
          { id: "8973" },
          { id: "6086" },
          { id: "10372" },
        ],
      },
      {
        teamName: "Penny",
        players: [
          { id: "9478" },
          { id: "11378" },
          { id: "10980" },
          { id: "4513" },
          { id: "1651" },
          { id: "9243" },
          { id: "4832046" },
          { id: "91" },
        ],
      },
      {
        teamName: "Jeff",
        players: [
          { id: "3470" },
          { id: "11099" },
          { id: "158" },
          { id: "308" },
          { id: "9037" },
          { id: "10505" },
          { id: "6086" },
          { id: "4304" },
        ],
      },
      {
        teamName: "Audra",
        players: [
          { id: "10046" },
          { id: "11099" },
          { id: "9877" },
          { id: "4513" },
          { id: "10166" },
          { id: "5550" },
          { id: "6086" },
          { id: "10058" },
        ],
      },
      {
        teamName: "Jason",
        players: [
          { id: "3470" },
          { id: "11099" },
          { id: "9126" },
          { id: "11382" },
          { id: "10166" },
          { id: "11250" },
          { id: "10596" },
          { id: "4304" },
        ],
      },
      {
        teamName: "Katie",
        players: [
          { id: "9478" },
          { id: "4410932" },
          { id: "11119" },
          { id: "11382" },
          { id: "9530" },
          { id: "3792" },
          { id: "6086" },
          { id: "5203536" },
        ],
      },
      {
        teamName: "Bobby",
        players: [
          { id: "9478" },
          { id: "4410932" },
          { id: "10980" },
          { id: "11382" },
          { id: "10054" },
          { id: "8973" },
          { id: "4425898" },
          { id: "4304" },
        ],
      },
      {
        teamName: "Scott",
        players: [
          { id: "3470" },
          { id: "4587" },
          { id: "9126" },
          { id: "9938" },
          { id: "676" },
          { id: "9243" },
          { id: "10596" },
          { id: "3980" },
        ],
      },
      {
        teamName: "RJ",
        players: [
          { id: "9478" },
          { id: "6007" },
          { id: "11119" },
          { id: "11382" },
          { id: "9037" },
          { id: "8973" },
          { id: "6086" },
          { id: "65" },
        ],
      },
      {
        teamName: "Brad",
        players: [
          { id: "9478" },
          { id: "4410932" },
          { id: "4602673" },
          { id: "4513" },
          { id: "4425906" },
          { id: "8973" },
          { id: "3449" },
          { id: "10372" },
        ],
      },
      {
        teamName: "Emily",
        players: [
          { id: "3470" },
          { id: "4364873" },
          { id: "8961" },
          { id: "4513" },
          { id: "10166" },
          { id: "6937" },
          { id: "6086" },
          { id: "686" },
        ],
      },
      {
        teamName: "Kaiser",
        players: [
          { id: "3470" },
          { id: "6007" },
          { id: "9877" },
          { id: "4513" },
          { id: "4425906" },
          { id: "11250" },
          { id: "1097" },
          { id: "10372" },
        ],
      },
      {
        teamName: "Seth",
        players: [
          { id: "10592" },
          { id: "6007" },
          { id: "4602673" },
          { id: "388" },
          { id: "676" },
          { id: "9243" },
          { id: "6086" },
          { id: "4304" },
        ],
      },
      {
        teamName: "Adam",
        players: [
          { id: "3470" },
          { id: "6007" },
          { id: "9126" },
          { id: "569" },
          { id: "4425906" },
          { id: "8973" },
          { id: "4425898" },
          { id: "5214992" },
        ],
      },
      {
        teamName: "Max",
        players: [
          { id: "9478" },
          { id: "4587" },
          { id: "1680" },
          { id: "3448" },
          { id: "9037" },
          { id: "10505" },
          { id: "6086" },
          { id: "10058" },
        ],
      },
      {
        teamName: "Steven",
        players: [
          { id: "3470" },
          { id: "4364873" },
          { id: "10980" },
          { id: "5285" },
          { id: "9037" },
          { id: "8973" },
          { id: "4901368" },
          { id: "65" },
        ],
      },
      {
        teamName: "Joe",
        players: [
          { id: "9478" },
          { id: "5539" },
          { id: "9877" },
          { id: "9025" },
          { id: "10166" },
          { id: "10505" },
          { id: "1097" },
          { id: "10058" },
        ],
      },
    ],
    tournamentPlayers: [
      { name: "Scottie Scheffler" },
      { name: "Rory McIlroy" },
      { name: "Jon Rahm" },
      { name: "Collin Morikawa" },
      { name: "Bryson DeChambeau" },
      { name: "Xander Schauffele" },
      { name: "Ludvig Aberg" },
      { name: "Justin Thomas" },
      { name: "Brooks Koepka" },
      { name: "Hideki Matsuyama" },
      { name: "Jordan Spieth" },
      { name: "Joaquin Niemann" },
      { name: "Viktor Hovland" },
      { name: "Tommy Fleetwood" },
      { name: "Patrick Cantlay" },
      { name: "Tyrrell Hatton" },
      { name: "Shane Lowry" },
      { name: "Russell Henley" },
      { name: "Cameron Smith" },
      { name: "Min Woo Lee" },
      { name: "Robert MacIntyre" },
      { name: "Akshay Bhatia" },
      { name: "Will Zalatoris" },
      { name: "Sergio Garcia" },
      { name: "Corey Conners" },
      { name: "Tony Finau" },
      { name: "Sepp Straka" },
      { name: "Jason Day" },
      { name: "Wyndham Clark" },
      { name: "Tom Kim" },
      { name: "Brian Harman" },
      { name: "Sahith Theegala" },
      { name: "Patrick Reed" },
      { name: "Keegan Bradley" },
      { name: "Dustin Johnson" },
      { name: "Aaron Rai" },
      { name: "Daniel Berger" },
      { name: "Sungjae Im" },
      { name: "Phil Mickelson" },
      { name: "Justin Rose" },
      { name: "Davis Thompson" },
      { name: "Byeong Hun An" },
      { name: "Sam Burns" },
      { name: "Adam Scott" },
      { name: "J.J. Spaun" },
      { name: "Taylor Pendrith" },
      { name: "Matt Fitzpatrick" },
      { name: "Lucas Glover" },
      { name: "Maverick McNealy" },
      { name: "Billy Horschel" },
      { name: "Michael Kim" },
      { name: "Thomas Detry" },
      { name: "Denny McCarthy" },
      { name: "Harris English" },
      { name: "Cameron Young" },
      { name: "Laurie Canter" },
      { name: "Stephan Jaeger" },
      { name: "Nicolai Hojgaard" },
      { name: "Rasmus Hojgaard" },
      { name: "Max Greyserman" },
      { name: "J.T. Poston" },
      { name: "Nick Taylor" },
      { name: "Max Homa" },
      { name: "Cam Davis" },
      { name: "Joe Highsmith" },
      { name: "Christiaan Bezuidenhout" },
      { name: "Tom Hoge" },
      { name: "Nico Echavarria" },
      { name: "Chris Kirk" },
      { name: "Austin Eckroat" },
      { name: "Nick Dunlap" },
      { name: "Kevin Yu" },
      { name: "Matthieu Pavon" },
      { name: "Charl Schwartzel" },
      { name: "Bubba Watson" },
      { name: "Matt McCarty" },
      { name: "Jhonattan Vegas" },
      { name: "Davis Riley" },
      { name: "Danny Willett" },
      { name: "Adam Schenk" },
      { name: "Zach Johnson" },
      { name: "Thriston Lawrence" },
      { name: "Justin Hastings" },
      { name: "Brian Campbell" },
      { name: "Jose Luis Ballester" },
      { name: "Patton Kizzire" },
      { name: "Evan Beck" },
      { name: "Angel Cabrera" },
      { name: "Noah Kent" },
      { name: "Bernhard Langer" },
      { name: "Rafael Campos" },
      { name: "Hiroshi Tai" },
      { name: "Mike Weir" },
      { name: "Fred Couples" },
      { name: "Jose Maria Olazabal" },
    ],
  }),
});
